name: quadrature-ML
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - joblib
  - matplotlib
  - scikit-learn=0.22.1
  - tensorflow=2.1
  - nb_conda
  - jupyter
